/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Dell
 */
public class FINDTEAM extends javax.swing.JFrame {
 
    /**
     * Creates new form FINDTEAM
     */
    public FINDTEAM() {
        initComponents();
        table_update();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtpeople = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtlocation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdatentime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtsport = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 164, 67));

        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "SPORT", "PEOPLE", "LOCATION", "D&T"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 929, 533));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel2.setText("PEOPLE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 136, 32));

        txtpeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpeopleActionPerformed(evt);
            }
        });
        getContentPane().add(txtpeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 225, 32));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel3.setText("LOCATION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 136, 32));

        txtlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlocationActionPerformed(evt);
            }
        });
        getContentPane().add(txtlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 225, 32));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel4.setText("DATENTIME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 136, 32));

        txtdatentime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatentimeActionPerformed(evt);
            }
        });
        getContentPane().add(txtdatentime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 225, 32));

        jLabel5.setText("UPAR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 90));

        jLabel6.setFont(new java.awt.Font("Swis721 Blk BT", 3, 24)); // NOI18N
        jLabel6.setText("FIND TEAMMATES");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 320, -1));

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 170, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel8.setText("SPORT");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 136, 32));

        txtsport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsportActionPerformed(evt);
            }
        });
        getContentPane().add(txtsport, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 225, 32));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\SWIMMINGGRADIANT.jpg")); // NOI18N
        jLabel1.setText("PURA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 1440, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsportActionPerformed
Connection con1;
PreparedStatement insert;
private void table_update() {
        int CC;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/mpr","root","MyNewPass");
            insert = con1.prepareStatement("SELECT * FROM FINDTEAM");
            ResultSet Rs = insert.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) TABLE.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
           
               
                    v2.add(Rs.getString("SPORT"));
                    v2.add(Rs.getString("PEOPLE"));
                    v2.add(Rs.getString("LOCATION"));
                    v2.add(Rs.getString("DATETIME"));
                
                DFT.addRow(v2);
            }
        } catch (Exception e) {
        }
    }



    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String SPORT =txtsport.getText();
String PEOPLE =txtpeople.getText();
String LOCATION =txtlocation.getText();
String DNT = txtdatentime.getText();





      try {
          Class.forName("com.mysql.jdbc.Driver"); //Register the mysql driver
          con1 = DriverManager.getConnection("jdbc:mysql://localhost/mpr","root","MyNewPass");
          insert = con1.prepareStatement("insert into FINDTEAM (SPORT,PEOPLE,LOCATION,DATETIME)values(?,?,?,?)");
          insert.setString(1,SPORT);
          insert.setString(2,PEOPLE);
          insert.setString(3,LOCATION);
          insert.setString(4,DNT);
          insert.executeUpdate();
          JOptionPane.showMessageDialog(this, "Record Saved");
          
          
          txtsport.setText("");
          txtpeople.setText("");
          txtlocation.setText("");
          txtdatentime.setText("");
          table_update();

      } catch (ClassNotFoundException ex) {
          Logger.getLogger(FINDTEAM.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(FINDTEAM.class.getName()).log(Level.SEVERE, null, ex);
      }      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtpeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpeopleActionPerformed

    private void txtlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocationActionPerformed

    private void txtdatentimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatentimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatentimeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            int row = TABLE.getSelectedRow(); // Get the selected row in the table
    
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Delete Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get the value in the first column (assumed to be the primary key) of the selected row
    String sportToDelete = TABLE.getModel().getValueAt(row, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/mpr", "root", "MyNewPass");
            PreparedStatement delete = con1.prepareStatement("DELETE FROM FINDTEAM WHERE SPORT = ?");
            delete.setString(1, sportToDelete);
            delete.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Deleted");
            table_update();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FINDTEAM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }     
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FINDTEAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FINDTEAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FINDTEAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FINDTEAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FINDTEAM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtdatentime;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtpeople;
    private javax.swing.JTextField txtsport;
    // End of variables declaration//GEN-END:variables
}
