/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Dell
 */
public class SwimmingCoachGUI extends javax.swing.JPanel {

    /**
     * Creates new form testing
     */
    public SwimmingCoachGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\Optimized-swimmingcoachtest2.jpg")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 313, 260, 220));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\Optimized-swimming coachtest.jpg")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 266, 222));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 271, 1060, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("MR Gopal Krishna");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 52, 180, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 2, 16)); // NOI18N
        jLabel4.setText("EXP 15 years + 3x Asian Cup Gold Medalist!!");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 141, 421, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Price = 5000/month");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 170, 35));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("MR Ravi Jaishankar");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 190, 35));

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 2, 16)); // NOI18N
        jLabel7.setText("EXP 21 years + Trained 5 Asian Cup Medal WINNERS!!");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 421, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("Price = 6000/month");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 170, 35));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\SWIMMINGGRADIANT.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1000, 650));
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
